import random
from typing import List, Dict, Union
from typing import Optional
from p_models.ability_info import AbilityInfo

# availableAbilities 리스트
available_abilities: List[AbilityInfo] = [
    AbilityInfo(0, '없음'),
    AbilityInfo(1, '엽록소', util=['rank_buff']),
    AbilityInfo(2, '선파워', offensive=['rank_buff']),
    AbilityInfo(3, '급류', offensive=['damage_buff']),
    AbilityInfo(4, '맹화', offensive=['damage_buff']),
    AbilityInfo(5, '심록', offensive=['damage_buff']),
    AbilityInfo(6, '우격다짐', offensive=['damage_buff']),
    AbilityInfo(7, '가속', util=['rank_change']),
    AbilityInfo(8, '철주먹', offensive=['damage_buff']),
    AbilityInfo(9, '조가비갑옷', defensive=['critical_nullification']),
    AbilityInfo(10, '오기', util=['rank_change']),
    AbilityInfo(11, '이판사판', offensive=['damage_buff']),
    AbilityInfo(12, '심술꾸러기', util=['etc']),
    AbilityInfo(13, '방탄', defensive=['damage_nullification']),
    AbilityInfo(14, '변환자재', offensive=['type_change']),
    AbilityInfo(15, '위협', appear=['rank_change']),
    AbilityInfo(16, '리베로', offensive=['type_change']),
    AbilityInfo(17, '그래스메이커', appear=['field_change']),
    AbilityInfo(18, '스나이퍼', offensive=['damage_buff']),
    AbilityInfo(19, '천진', util=['rank_nullification']),
    AbilityInfo(20, '변환자재', offensive=['type_change']),
    AbilityInfo(21, '자기과신', offensive=['rank_change']),
    AbilityInfo(22, '타오르는불꽃', defensive=['type_nullification']),
    AbilityInfo(23, '재생력', util=['change_trigger']),
    AbilityInfo(24, '가뭄', appear=['weather_change']),
    AbilityInfo(25, '승기', defensive=['rank_change']),
    AbilityInfo(26, '테크니션', offensive=['damage_buff']),
    AbilityInfo(27, '불꽃몸', defensive=['status_change']),
    AbilityInfo(28, '쓱쓱', util=['rank_buff']),
    AbilityInfo(29, '독가시', defensive=['status_change']),
    AbilityInfo(30, '저수', defensive=['type_nullification']),
    AbilityInfo(31, '벌레의알림', offensive=['damage_buff']),
    AbilityInfo(32, '메가런처', offensive=['damage_buff']),
    AbilityInfo(33, '불면', util=['status_nullification']),
    AbilityInfo(34, '부식', util=['etc']),
    AbilityInfo(35, '수포', offensive=['damage_buff'], util=['status_nullification']),
    AbilityInfo(36, '여왕의위엄', defensive=['damage_nullification']),
    AbilityInfo(37, '증기기관', defensive=['rank_change']),
    AbilityInfo(38, '적응력', offensive=['damage_buff']),
    AbilityInfo(39, '의욕', offensive=['damage_buff']),
    AbilityInfo(40, '깨어진갑옷', defensive=['rank_change']),
    AbilityInfo(41, '변덕쟁이', util=['rank_change']),
    AbilityInfo(42, '리프가드', util=['status_nullification']),
    AbilityInfo(43, '정의의마음', defensive=['rank_change']),
    AbilityInfo(44, '마이페이스', util=['status_nullification', 'intimidate_nullification']),
    AbilityInfo(45, '둔감', util=['status_nullification', 'intimidate_nullification']),
    AbilityInfo(46, '하얀연기', util=['rank_nullification']),
    AbilityInfo(47, '클리어바디', util=['rank_nullification']),
    AbilityInfo(48, '메탈프로텍트', util=['rank_nullification']),
    AbilityInfo(49, '이상한비늘', defensive=['damage_reduction']),
    AbilityInfo(50, '포자', defensive=['status_change']),
    AbilityInfo(51, '의기양양', util=['status_nullification']),
    AbilityInfo(52, '수의베일', util=['status_nullification']),
    AbilityInfo(53, '자연회복', util=['etc']),
    AbilityInfo(54, '독수', offensive=['status_change']),
    AbilityInfo(55, '질풍날개', util=['etc']),
    AbilityInfo(56, '틀깨기', offensive=['ability_nullification']),
    AbilityInfo(57, '테라볼티지', offensive=['ability_nullification']),
    AbilityInfo(58, '터보블레이즈', offensive=['ability_nullification']),
    AbilityInfo(59, '균사의힘', offensive=['ability_nullification']),
    AbilityInfo(60, '곡예', util=['rank_buff']),
    AbilityInfo(61, '정전기', defensive=['status_change']),
    AbilityInfo(62, '피뢰침', defensive=['type_nullification']),
    AbilityInfo(63, '매직가드', util=['tickDamage_nullification']),
    AbilityInfo(64, '싱크로', defensive=['status_change']),
    AbilityInfo(65, '전투무장', defensive=['critical_nullification']),
    AbilityInfo(66, '프레셔', util=['etc']),
    AbilityInfo(67, '면역', util=['status_nullification']),
    AbilityInfo(68, '두꺼운지방', defensive=['damage_reduction']),
    AbilityInfo(69, '정신력', util=['intimidate_nullification', 'status_nullification']),
    AbilityInfo(70, '매직미러', util=['statusMove_nullification']),
    AbilityInfo(71, '트레이스', appear=['ability_change']),
    AbilityInfo(72, '옹골참', util=['etc']),
    AbilityInfo(73, '부유', defensive=['type_nullification']),
    AbilityInfo(74, '방음', defensive=['damage_nullification']),
    AbilityInfo(75, '대운', util=['rank_buff']),
    AbilityInfo(76, '내열', defensive=['damage_reduction']),
    AbilityInfo(77, '마중물', defensive=['type_nullification']),
    AbilityInfo(78, '모래날림', appear=['weather_change']),
    AbilityInfo(79, '모래숨기', util=['rank_buff']),
    AbilityInfo(80, '눈퍼뜨리기', appear=['weather_change']),
    AbilityInfo(81, '돌머리', offensive=['remove_demerit']),
    AbilityInfo(82, '건조피부', defensive=['type_nullification'], util=['heal']),
    AbilityInfo(83, '애널라이즈', offensive=['damage_buff']),
    AbilityInfo(84, '하드록', defensive=['damage_reduction']),
    AbilityInfo(85, '하늘의은총', util=['etc']),
    AbilityInfo(86, '전기엔진', defensive=['type_nullification'], util=['rank_change']),
    AbilityInfo(87, '색안경', offensive=['damage_buff']),
    AbilityInfo(88, '눈숨기', util=['rank_buff']),
    AbilityInfo(89, '아이스바디', util=['heal']),
    AbilityInfo(90, '포이즌힐', util=['heal']),
    AbilityInfo(91, '다운로드', appear=['rank_change']),
    AbilityInfo(92, '예리함', offensive=['damage_buff']),
    AbilityInfo(93, '배짱', offensive=['type_nullification'], util=['intimidate_nullification']),
    AbilityInfo(94, '초식', defensive=['type_nullification']),
    AbilityInfo(95, '모래헤치기', util=['rank_buff']),
    AbilityInfo(96, '미라클스킨', defensive=['status_change'], util=['statusMove_nullification']),
    AbilityInfo(97, '무기력', offensive=['demerit'], util=['demerit']),
    AbilityInfo(98, '복안', util=['rank_buff']),
    AbilityInfo(99, '눈치우기', util=['rank_buff']),
    AbilityInfo(100, '노가드', util=['certainly']),
    AbilityInfo(101, '방진', defensive=['damage_nullification'], util=['status_nullification']),
    AbilityInfo(102, '부풀린가슴', offensive=['rank_buff']),
    AbilityInfo(103, '플라워베일', util=['status_nullification']),
    AbilityInfo(104, '짓궂은마음', util=['etc']),
    AbilityInfo(105, '옹골찬턱', offensive=['damage_buff']),
    AbilityInfo(106, '프리즈스킨', offensive=['damage_buff']),
    AbilityInfo(107, '페어리스킨', offensive=['damage_buff']),
    AbilityInfo(108, '틈새포착', util=['etc']),
    AbilityInfo(109, '단단한발톱', offensive=['damage_buff']),
    AbilityInfo(110, '어군', util=['form_change']),
    AbilityInfo(111, '지구력', defensive=['rank_change']),
    AbilityInfo(112, '힐링시프트', util=['etc']),
    AbilityInfo(113, '위기회피', util=['etc']),
    AbilityInfo(114, 'AR시스템', appear=['form_change']),
    AbilityInfo(115, '강철술사', offensive=['damage_buff']),
    AbilityInfo(116, '미러아머', util=['etc']),
    AbilityInfo(117, '모래뿜기', defensive=['weather_change']),
    AbilityInfo(118, '탈피', util=['etc']),
    AbilityInfo(119, '펑크록', offensive=['damage_buff'], defensive=['damage_reduction']),
    AbilityInfo(120, '저주받은바디', defensive=['status_change'])
]

# abilityData 함수 변환
def ability_data(abilities: List[str]) -> AbilityInfo:
    selected = [
        ability for ability in available_abilities
        if ability.name in abilities
    ]

    invalid_names = [name for name in abilities if not any(ability.name == name for ability in available_abilities)]

    if invalid_names:
        print(f"[abilityData] 유효하지 않은 특성 이름{'들' if len(invalid_names) > 1 else ''} 감지됨:\n- " + "\n- ".join(invalid_names))
        return available_abilities[0]  # fallback: '없음' 리턴

    return random.choice(selected)