# env/mock_pokemon.py
from typing import List
from p_models.pokemon_info import PokemonInfo
from p_data.move_data import move_data
from p_data.ability_data import ability_data

def create_mock_pokemon_list() -> List[PokemonInfo]:
    return [
        PokemonInfo(
            id=3,
            name='이상해꽃',
            types=['풀', '독'],
            moves=move_data(['대지의힘', '씨뿌리기', '광합성', '기가드레인', '오물폭탄', '수면가루', '맹독', '에너지볼'], ['풀', '독']),
            sex='male',
            ability=ability_data(['엽록소', '심록']),
            hp=80,
            attack=82,
            sp_attack=100,
            defense=83,
            sp_defense=100,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=6,
            name='리자몽',
            types=['불', '비행'],
            moves=move_data(['에어슬래시', '불대문자', '오버히트', '지진', '니트로차지', '화염방사', '폭풍', '용의파동', '원시의힘'], ['불', '비행']),
            sex='male',
            ability=ability_data(['맹화', '선파워']),
            hp=78,
            attack=84,
            sp_attack=109,
            defense=78,
            sp_defense=85,
            speed=100,
            level=50
        ),
        PokemonInfo(
            id=9,
            name='거북왕',
            types=['물'],
            moves=move_data(['껍질깨기', '하이드로펌프', '냉동빔', '악의파동', '아쿠아제트', '퀵턴', '파동탄', '러스터캐논', '지진'], ['물']),
            sex='male',
            ability=ability_data(['급류']),
            hp=79,
            attack=83,
            sp_attack=85,
            defense=100,
            sp_defense=105,
            speed=78,
            level=50
        ),
        PokemonInfo(
            id=26,
            name='라이츄',
            types=['전기'],
            moves=move_data(['볼부비부비', '나쁜음모', '10만볼트', '개척하기', '볼트체인지', '구멍파기', '풀묶기', '파도타기', '치근거리기', '와일드볼트', '기합구슬', '일렉트릭네트'], ['전기']),
            sex='male',
            ability=ability_data(['피뢰침', '정전기']),
            hp=60,
            attack=90,
            defense=55,
            sp_attack=90,
            sp_defense=80,
            speed=110,
            level=50
        ),
        PokemonInfo(
            id=34,
            name='니드킹',
            types=['독', '땅'],
            moves=move_data(['독찌르기', '지진', '스톤샤워', '암석봉인', '불꽃펀치', '냉동펀치', '번개펀치', '파도타기', '메가혼', '엄청난힘', '기습', '오물폭탄', '대지의힘'], ['땅', '독']),
            sex='male',
            ability=ability_data(['우격다짐', '독가시']),
            hp=81,
            attack=102,
            defense=77,
            sp_attack=85,
            sp_defense=75,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=59,
            name='윈디',
            types=['불'],
            moves=move_data(['플레어드라이브', '신속', '치근거리기', '와일드볼트', '인파이트', '깨물어부수기', '니트로차지', '땅고르기', '도깨비불'], ['불']),
            sex='male',
            ability=ability_data(['위협', '타오르는불꽃', '정의의마음']),
            hp=90,
            attack=110,
            defense=80,
            sp_attack=100,
            sp_defense=80,
            speed=95,
            level=50
        ),
        PokemonInfo(
            id=65,
            name='후딘',
            types=['에스퍼'],
            moves=move_data(['사이코키네시스', '냉동빔', '에너지볼', '기합구슬', '불대문자', '섀도볼', '전기자석파', '나쁜음모', '차지빔', 'HP회복', '매지컬샤인'], ['에스퍼']),
            sex='male',
            ability=ability_data(['매직가드', '싱크로']),
            hp=55,
            attack=50,
            defense=45,
            sp_attack=135,
            sp_defense=95,
            speed=120,
            level=50
        ),
        PokemonInfo(
            id=94,
            name='팬텀',
            types=['고스트', '독'],
            moves=move_data(['오물폭탄', '섀도볼', '기합구슬', '사이코키네시스', '매지컬샤인', '전기자석파', '이상한빛', '얼어붙은바람', '나쁜음모', '기가드레인', '10만볼트'], ['고스트', '독']),
            sex='male',
            ability=ability_data(['저주받은바디']),
            hp=60,
            attack=65,
            defense=60,
            sp_attack=130,
            sp_defense=75,
            speed=110,
            level=50
        ),
        PokemonInfo(
            id=103,
            name='나시',
            types=['풀', '에스퍼'],
            moves=move_data(['에너지볼', '씨뿌리기', '사이코키네시스', '오물폭탄', '기가드레인', '땅고르기', '리프스톰', '광합성'], ['풀', '에스퍼']),
            sex='male',
            ability=ability_data(['엽록소']),
            hp=95,
            attack=95,
            defense=85,
            sp_attack=125,
            sp_defense=65,
            speed=55,
            level=50
        ),
        PokemonInfo(
            id=130,
            name='갸라도스',
            types=['물', '비행'],
            moves=move_data(['폭포오르기', '깨물어부수기', '용의춤', '지진', '스톤에지', '열불내기', '눈사태', '아이언헤드', '전기자석파'], ['물', '비행']),
            sex='male',
            ability=ability_data(['위협', '자기과신']),
            hp=95,
            attack=125,
            defense=79,
            sp_attack=60,
            sp_defense=100,
            speed=81,
            level=50
        ),
        PokemonInfo(
            id=131,
            name='라프라스',
            types=['물', '얼음'],
            moves=move_data(['냉동빔', '하이드로펌프', '얼어붙은바람', '얼음뭉치', '파도타기', '절대영도', '이상한빛', '10만볼트', '매혹의보이스', '지진', '땅고르기'], ['물', '얼음']),
            sex='male',
            ability=ability_data(['저수', '조가비갑옷']),
            hp=130,
            attack=85,
            defense=80,
            sp_attack=85,
            sp_defense=95,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=139,
            name='암스타',
            types=['바위', '물'],
            moves=move_data(['하이드로펌프', '원시의힘', '파도타기', '대지의힘', '암석봉인', '스텔스록', '껍질깨기', '얼어붙은바람', '냉동빔', '메테오빔'], ['물', '바위']),
            sex='male',
            ability=ability_data(['조가비갑옷', '깨어진갑옷']),
            hp=70,
            attack=60,
            defense=125,
            sp_attack=115,
            sp_defense=70,
            speed=55,
            level=50
        ),
        PokemonInfo(
            id=141,
            name='투구푸스',
            types=['바위', '물'],
            moves=move_data(['깜짝베기', '아쿠아제트', '아쿠아브레이크', '흡혈', '스톤에지', '암석봉인', '크로스포이즌', '칼춤'], ['바위', '물']),
            sex='male',
            ability=ability_data(['전투무장', '깨어진갑옷']),
            hp=60,
            attack=115,
            defense=105,
            sp_attack=65,
            sp_defense=70,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=142,
            name='프테라',
            types=['바위', '비행'],
            moves=move_data(['스톤샤워', '깨물어부수기', '용의춤', '공중날기', '더블윙', '아이언헤드', '지진', '스톤에지', '땅고르기', '번개엄니'], ['바위', '비행']),
            sex='male',
            ability=ability_data(['프레셔']),
            hp=80,
            attack=105,
            defense=65,
            sp_attack=60,
            sp_defense=75,
            speed=130,
            level=50
        ),
        PokemonInfo(
            id=143,
            name='잠만보',
            types=['노말'],
            moves=move_data(['누르기', '헤비봄버', '땅고르기', '암석봉인', '불꽃펀치', '번개펀치', '냉동펀치', '씨폭탄', '더스트슈트', '지진'], ['노말']),
            sex='male',
            ability=ability_data(['면역', '두꺼운지방']),
            hp=160,
            attack=110,
            defense=65,
            sp_attack=65,
            sp_defense=110,
            speed=30,
            level=50
        ),
        PokemonInfo(
            id=254,
            name='나무킹',
            types=['풀'],
            moves=move_data(['기가드레인', '용의파동', '씨뿌리기', '진공파', '에너지볼', '리프스톰', '암석봉인', '드래곤테일', '스톤샤워', '애크러뱃'], ['풀']),
            sex='male',
            ability=ability_data(['곡예', '심록']),
            hp=70,
            attack=85,
            defense=65,
            sp_attack=105,
            sp_defense=85,
            speed=120,
            level=50
        ),
        PokemonInfo(
            id=257,
            name='번치코',
            types=['불', '격투'],
            moves=move_data(['칼춤', '플레어드라이브', '스톤에지', '인파이트', '블레이즈킥', '번개펀치', '유턴', '파동탄', '지진', '브레이브버드', '진공파', '깜짝베기'], ['불', '격투']),
            sex='male',
            ability=ability_data(['가속', '맹화']),
            hp=80,
            attack=120,
            defense=70,
            sp_attack=110,
            sp_defense=70,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=260,
            name='대짱이',
            types=['물', '땅'],
            moves=move_data(['퀵턴', '아쿠아브레이크', '지진', '눈사태', '스톤샤워', '암석봉인', '독찌르기', '카운터', '냉동펀치', '스텔스록'], ['물', '땅']),
            sex='male',
            ability=ability_data(['급류']),
            hp=100,
            attack=110,
            defense=90,
            sp_attack=85,
            sp_defense=90,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=389,
            name='토대부기',
            types=['풀', '땅'],
            moves=move_data(['껍질깨기', '지진', '우드해머', '기가드레인', '아이언헤드', '스톤샤워', '들이받기', '스톤에지', '스텔스록', '깨물어부수기'], ['풀', '땅']),
            sex='male',
            ability=ability_data(['조가비갑옷', '심록']),
            hp=95,
            attack=109,
            defense=105,
            sp_attack=75,
            sp_defense=85,
            speed=56,
            level=50
        ),
        PokemonInfo(
            id=392,
            name='초염몽',
            types=['불', '격투'],
            moves=move_data(['플레어드라이브', '번개펀치', '드레인펀치', '지진', '마하펀치', '인파이트', '애크러뱃', '니트로차지', '유턴', '오버히트', '풀묶기', '더스트슈트', '화염방사'], ['불', '격투']),
            sex='male',
            ability=ability_data(['맹화', '철주먹']),
            hp=76,
            attack=104,
            defense=71,
            sp_attack=104,
            sp_defense=71,
            speed=108,
            level=50
        ),
        PokemonInfo(
            id=395,
            name='엠페르트',
            types=['물', '강철'],
            moves=move_data(['퀵턴', '하이드로펌프', '냉동빔', '풀묶기', '아쿠아제트', '러스터캐논', '에어슬래시', '암석봉인', '날개쉬기'], ['물', '강철']),
            sex='male',
            ability=ability_data(['오기', '급류']),
            hp=84,
            attack=86,
            defense=88,
            sp_attack=111,
            sp_defense=101,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=497,
            name='샤로다',
            types=['풀'],
            moves=move_data(['리프스톰', '기가드레인', '뱀눈초리', '용의파동', '드래곤테일', '에너지볼', '아쿠아테일'], ['풀']),
            sex='female',
            ability=ability_data(['심술꾸러기', '심록']),
            hp=75,
            attack=75,
            defense=95,
            sp_attack=75,
            sp_defense=95,
            speed=113,
            level=50
        ),
        PokemonInfo(
            id=500,
            name='염무왕',
            types=['불', '격투'],
            moves=move_data(['니트로차지', '플레어드라이브', '양날박치기', '와일드볼트', '개척하기', '독찌르기', '인파이트', '지진', '풀묶기', '드레인펀치'], ['불', '격투']),
            sex='male',
            ability=ability_data(['맹화', '이판사판']),
            hp=110,
            attack=123,
            defense=65,
            sp_attack=100,
            sp_defense=65,
            speed=65,
            level=50
        ),
        PokemonInfo(
            id=503,
            name='대검귀',
            types=['물'],
            moves=move_data(['눈사태', '아쿠아브레이크', '퀵턴', '아쿠아제트', '풀묶기', '메가혼', '하이드로펌프', '에어슬래시', '땅고르기', '깜짝베기', '성스러운칼'], ['물']),
            sex='male',
            ability=ability_data(['급류', '조가비갑옷']),
            hp=95,
            attack=100,
            defense=85,
            sp_attack=108,
            sp_defense=70,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=652,
            name='브리가론',
            types=['풀', '격투'],
            moves=move_data(['씨기관총', '바디프레스', '광합성', '철벽', '맹독', '씨뿌리기', '바늘미사일', '암석봉인', '드레인펀치', '스톤샤워', '니들가드'], ['풀', '격투']),
            sex='male',
            ability=ability_data(['방탄', '심록']),
            hp=88,
            attack=107,
            defense=122,
            sp_attack=74,
            sp_defense=75,
            speed=64,
            level=50
        ),
        PokemonInfo(
            id=655,
            name='마폭시',
            types=['불', '에스퍼'],
            moves=move_data(['매지컬플레임', '사이코키네시스', '에너지볼', '명상', '섀도볼', '불대문자', '이상한빛', '화염방사', '매지컬샤인'], ['불', '에스퍼']),
            sex='female',
            ability=ability_data(['맹화']),
            hp=75,
            attack=69,
            defense=72,
            sp_attack=114,
            sp_defense=100,
            speed=104,
            level=50
        ),
        PokemonInfo(
            id=658,
            name='개굴닌자',
            types=['물', '악'],
            moves=move_data(['풀묶기', '하이드로펌프', '물수리검', '악의파동', '냉동빔', '독압정', '깜짝베기', '더스트슈트', '애크러뱃', '유턴'], ['물', '악']),
            sex='male',
            ability=ability_data(['변환자재', '급류']),
            hp=72,
            attack=95,
            defense=67,
            sp_attack=103,
            sp_defense=71,
            speed=122,
            level=50
        ),
        PokemonInfo(
            id=727,
            name='어흥염',
            types=['불', '악'],
            moves=move_data(['플레어드라이브', '도깨비불', '막말내뱉기', 'DD래리어트', '지진', '인파이트', '개척하기', '번개펀치', '불꽃펀치', '크로스촙'], ['불', '악']),
            sex='male',
            ability=ability_data(['위협', '맹화']),
            hp=95,
            attack=115,
            defense=90,
            sp_attack=80,
            sp_defense=90,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=724,
            name='모크나이퍼',
            types=['풀', '고스트'],
            moves=move_data(['리프블레이드', '칼춤', '폴터가이스트', '더블윙', '야습', '브레이브버드', '애크러뱃', '이상한빛', '개척하기', '섀도클로'], ['풀', '고스트']),
            sex='male',
            ability=ability_data(['심록']),
            hp=78,
            attack=107,
            defense=75,
            sp_attack=100,
            sp_defense=100,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=730,
            name='누리레느',
            types=['물', '페어리'],
            moves=move_data(['물거품아리아', '문포스', '퀵턴', '아쿠아제트', '에너지볼', '냉동빔', '섀도볼', '사이코키네시스', '드레인키스'], ['물', '페어리']),
            sex='female',
            ability=ability_data(['급류']),
            hp=80,
            attack=74,
            defense=74,
            sp_attack=126,
            sp_defense=116,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=815,
            name='에이스번',
            types=['불'],
            moves=move_data(['화염볼', '무릎차기', '칼춤', '유턴', '애크러뱃', '개척하기', '아이언헤드', '더스트슈트', '니트로차지'], ['불']),
            sex='female',
            ability=ability_data(['맹화', '리베로']),
            hp=80,
            attack=116,
            defense=75,
            sp_attack=65,
            sp_defense=75,
            speed=119,
            level=50
        ),
        PokemonInfo(
            id=812,
            name='고릴타',
            types=['풀'],
            moves=move_data(['그래스슬라이더', '10만마력', '칼춤', '우드해머', '드럼어택', '애크러뱃', '개척하기', '드레인펀치', '로킥'], ['풀']),
            sex='male',
            ability=ability_data(['그래스메이커', '심록']),
            hp=100,
            attack=125,
            defense=90,
            sp_attack=60,
            sp_defense=70,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=818,
            name='인텔리레온',
            types=['물'],
            moves=move_data(['기충전', '열탕', '냉동빔', '섀도볼', '에어커터', '하이드로펌프', '아쿠아제트', '악의파동'], ['물']),
            sex='male',
            ability=ability_data(['스나이퍼', '급류']),
            hp=70,
            attack=85,
            defense=65,
            sp_attack=125,
            sp_defense=65,
            speed=120,
            level=50
        ),
        PokemonInfo(
            id=911,
            name='라우드본',
            types=['불', '고스트'],
            moves=move_data(['플레어송', '게으름피우기', '섀도볼', '도깨비불', '오버히트', '대지의힘', '씨폭탄', '매혹의보이스'], ['불', '고스트']),
            sex='male',
            ability=ability_data(['맹화', '천진']),
            hp=104,
            attack=75,
            defense=100,
            sp_attack=110,
            sp_defense=75,
            speed=66,
            level=50
        ),
        PokemonInfo(
            id=908,
            name='마스카나',
            types=['풀', '악'],
            moves=move_data(['트릭플라워', '유턴', '깜짝베기', '치근거리기', '애크러뱃', '개척하기', '로킥', '트리플악셀', '찬물끼얹기'], ['풀', '악']),
            sex='female',
            ability=ability_data(['변환자재', '심록']),
            hp=76,
            attack=110,
            defense=70,
            sp_attack=81,
            sp_defense=70,
            speed=123,
            level=50
        ),
        PokemonInfo(
            id=914,
            name='웨이니발',
            types=['물', '격투'],
            moves=move_data(['아쿠아스텝', '웨이브태클', '인파이트', '브레이브버드', '아쿠아브레이크', '트리플악셀', '로킥', '유턴'], ['물', '격투']),
            sex='male',
            ability=ability_data(['자기과신', '급류']),
            hp=85,
            attack=120,
            defense=80,
            sp_attack=85,
            sp_defense=75,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=154,
            name='메가니움',
            types=['풀'],
            moves=move_data(['씨뿌리기', '기가드레인', '광합성', '맹독', '방어', '에너지볼', '원시의힘', '지진', '바디프레스', '드래곤테일'], ['풀']),
            sex='female',
            ability=ability_data(['심록', '리프가드']),
            hp=80,
            attack=82,
            defense=100,
            sp_attack=83,
            sp_defense=100,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=157,
            name='블레이범',
            types=['불'],
            moves=move_data(['니트로차지', '오버히트', '불대문자', '와일드볼트', '지진', '치근거리기', '암석봉인', '섀도볼', '화염방사'], ['불']),
            sex='male',
            ability=ability_data(['맹화', '타오르는불꽃']),
            hp=76,
            attack=104,
            defense=71,
            sp_attack=104,
            sp_defense=71,
            speed=108,
            level=50
        ),
        PokemonInfo(
            id=160,
            name='장크로다일',
            types=['물'],
            moves=move_data(['용의춤', '아쿠아브레이크', '냉동펀치', '엄청난힘', '스톤샤워', '아쿠아제트', '깨물어부수기', '개척하기', '눈사태'], ['물']),
            sex='male',
            ability=ability_data(['급류', '우격다짐']),
            hp=85,
            attack=105,
            defense=100,
            sp_attack=79,
            sp_defense=83,
            speed=78,
            level=50
        ),
        PokemonInfo(
            id=169,
            name='크로뱃',
            types=['독', '비행'],
            moves=move_data(['크로스포이즌', '애크러뱃', '흡혈', '이상한빛', '기가드레인', '유턴', '맹독', '브레이브버드', '더블윙', '날개쉬기'], ['독', '비행']),
            sex='male',
            ability=ability_data(['정신력']),
            hp=85,
            attack=90,
            defense=80,
            sp_attack=70,
            sp_defense=80,
            speed=130,
            level=50
        ),
        PokemonInfo(
            id=181,
            name='전룡',
            types=['전기'],
            moves=move_data(['10만볼트', '전기자석파', '기합구슬', '파워젬', '시그널빔', '용의파동', '이상한빛', '일렉트릭네트', '볼트체인지', '매지컬샤인'], ['전기']),
            sex='male',
            ability=ability_data(['정전기']),
            hp=90,
            attack=75,
            defense=85,
            sp_attack=115,
            sp_defense=90,
            speed=55,
            level=50
        ),
        PokemonInfo(
            id=182,
            name='아르코',
            types=['풀'],
            moves=move_data(['나비춤', '수면가루', '문포스', '기가드레인', '오물폭탄', '힘흡수', '에너지볼'], ['풀']),
            sex='male',
            ability=ability_data(['엽록소']),
            hp=75,
            attack=80,
            defense=95,
            sp_attack=90,
            sp_defense=100,
            speed=50,
            level=50
        ),
        PokemonInfo(
            id=196,
            name='에브이',
            types=['에스퍼'],
            moves=move_data(['사이코키네시스', '이상한빛', '풀묶기', '파워젬', '섀도볼', '전기자석파', '매혹의보이스'], ['에스퍼']),
            sex='male',
            ability=ability_data(['싱크로', '매직미러']),
            hp=65,
            attack=65,
            defense=60,
            sp_attack=130,
            sp_defense=95,
            speed=110,
            level=50
        ),
        PokemonInfo(
            id=199,
            name='야도킹',
            types=['물', '에스퍼'],
            moves=move_data(['사이코키네시스', '하이드로펌프', '냉동빔', '기합구슬', '풀묶기', '트릭룸', '불대문자', '열탕'], ['물', '에스퍼']),
            sex='male',
            ability=ability_data(['재생력', '마이페이스', '둔감']),
            hp=95,
            attack=75,
            defense=80,
            sp_attack=100,
            sp_defense=110,
            speed=30,
            level=50
        ),
        PokemonInfo(
            id=212,
            name='핫삼',
            types=['벌레', '강철'],
            moves=move_data(['불릿펀치', '유턴', '칼춤', '애크러뱃', '아이언헤드', '개척하기', '덤벼들기', '깜짝베기', '카운터'], ['벌레', '강철']),
            sex='male',
            ability=ability_data(['테크니션']),
            hp=70,
            attack=130,
            defense=100,
            sp_attack=55,
            sp_defense=80,
            speed=65,
            level=50
        ),
        PokemonInfo(
            id=214,
            name='헤라크로스',
            types=['벌레', '격투'],
            moves=move_data(['메가혼', '유턴', '개척하기', '씨기관총', '스톤에지', '지진', '인파이트', '암석봉인', '지옥찌르기'], ['벌레', '격투']),
            sex='male',
            ability=ability_data(['벌레의알림', '자기과신']),
            hp=80,
            attack=125,
            defense=75,
            sp_attack=40,
            sp_defense=95,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=229,
            name='헬가',
            types=['악', '불'],
            moves=move_data(['불대문자', '악의파동', '도깨비불', '개척하기', '섀도볼', '오버히트', '맹독', '화염방사', '오물폭탄', '기습'], ['악', '불']),
            sex='male',
            ability=ability_data(['타오르는불꽃']),
            hp=75,
            attack=90,
            defense=50,
            sp_attack=110,
            sp_defense=80,
            speed=95,
            level=50
        ),
        PokemonInfo(
            id=230,
            name='킹드라',
            types=['물', '드래곤'],
            moves=move_data(['하이드로펌프', '기충전', '얼어붙은바람', '냉동빔', '용의파동', '웨이브태클', '폭풍', '비바라기', '스케일샷', '아이언헤드'], ['물', '드래곤']),
            sex='male',
            ability=ability_data(['스나이퍼', '쓱쓱']),
            hp=75,
            attack=95,
            defense=95,
            sp_attack=95,
            sp_defense=95,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=324,
            name='코터스',
            types=['불'],
            moves=move_data(['분연', '화염방사', '오버히트', '스텔스록', '대지의힘', '오물폭탄', '솔라빔', '땅가르기'], ['불']),
            sex='male',
            ability=ability_data(['가뭄']),
            hp=70,
            attack=85,
            defense=140,
            sp_attack=85,
            sp_defense=70,
            speed=20,
            level=50
        ),
        PokemonInfo(
            id=350,
            name='밀로틱',
            types=['물'],
            moves=move_data(['하이드로펌프', '냉동빔', '드래곤테일', 'HP회복', '매혹의보이스', '드레인키스', '얼어붙은바람', '이상한빛', '열탕'], ['물']),
            sex='female',
            ability=ability_data(['승기', '이상한비늘']),
            hp=95,
            attack=60,
            defense=79,
            sp_attack=100,
            sp_defense=125,
            speed=81,
            level=50
        ),
        PokemonInfo(
            id=286,
            name='버섯모',
            types=['풀', '격투'],
            moves=move_data(['씨기관총', '마하펀치', '버섯포자', '드레인펀치', '독찌르기', '번개펀치', '발경', '암석봉인', '더스트슈트'], ['풀', '격투']),
            sex='male',
            ability=ability_data(['포자', '테크니션']),
            hp=60,
            attack=130,
            defense=80,
            sp_attack=60,
            sp_defense=60,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=282,
            name='가디안',
            types=['에스퍼', '페어리'],
            moves=move_data(['사이코키네시스', '문포스', '10만볼트', '에너지볼', '섀도볼', '진공파', '전기자석파', '이상한빛', '매지컬플레임', '얼어붙은바람'], ['에스퍼', '페어리']),
            ability=ability_data(['싱크로', '트레이스']),
            hp=68,
            attack=65,
            defense=65,
            sp_attack=125,
            sp_defense=115,
            speed=80,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=306,
            name='보스로라',
            types=['강철', '바위'],
            moves=move_data(['스톤샤워', '아이언헤드', '지진', '바디프레스', '암석봉인', '메탈버스트', '불꽃펀치', '냉동펀치', '번개펀치', '양날박치기'], ['강철', '바위']),
            ability=ability_data(['옹골참', '돌머리']),
            hp=70,
            attack=110,
            defense=180,
            sp_attack=60,
            sp_defense=60,
            speed=50,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=330,
            name='플라이곤',
            types=['땅', '드래곤'],
            moves=move_data(['지진', '스케일샷', '더블윙', '땅고르기', '개척하기', '용의춤', '엄청난힘', '스톤에지', '번개펀치', '불꽃펀치', '유턴', '만나자마자'], ['땅', '드래곤']),
            ability=ability_data(['부유']),
            hp=80,
            attack=100,
            defense=80,
            sp_attack=80,
            sp_defense=80,
            speed=100,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=346,
            name='릴리요',
            types=['바위', '풀'],
            moves=move_data(['에너지볼', '기가드레인', '암석봉인', '땅고르기', '지진', '오물폭탄', '스텔스록', '씨뿌리기', '미러코트', 'HP회복', '스톤에지'], ['바위', '풀']),
            ability=ability_data(['마중물']),
            hp=86,
            attack=81,
            defense=97,
            sp_attack=81,
            sp_defense=107,
            speed=43,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=348,
            name='아말도',
            types=['바위', '벌레'],
            moves=move_data(['스톤에지', '땅고르기', '암석봉인', '섀도클로', '크로스포이즌', '아쿠아제트', '록커트', '스텔스록', '덤벼들기'], ['바위', '벌레']),
            ability=ability_data(['전투무장', '쓱쓱']),
            hp=75,
            attack=125,
            defense=100,
            sp_attack=70,
            sp_defense=80,
            speed=45,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=365,
            name='씨카이저',
            types=['물', '얼음'],
            moves=move_data(['하이드로펌프', '얼음뭉치', '냉동빔', '절대영도', '얼어붙은바람', '암석봉인', '땅고르기', '파도타기', '아이언헤드'], ['물', '얼음']),
            ability=ability_data(['두꺼운지방', '둔감']),
            hp=110,
            attack=80,
            defense=90,
            sp_attack=95,
            sp_defense=90,
            speed=65,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=467,
            name='마그마번',
            types=['불'],
            moves=move_data(['불대문자', '화염방사', '10만볼트', '기합구슬', '사이코키네시스', '암석봉인', '이상한빛', '애시드봄'], ['불']),
            sex='male',
            ability=ability_data(['불꽃몸', '의기양양']),
            hp=75,
            attack=95,
            defense=67,
            sp_attack=125,
            sp_defense=95,
            speed=83,
            level=50
        ),
        PokemonInfo(
            id=419,
            name='플로젤',
            types=['물'],
            moves=move_data(['웨이브태클', '아쿠아제트', '아이언테일', '깨물어부수기', '퀵턴', '벌크업', '냉동펀치', '암석봉인'], ['물']),
            sex='male',
            ability=ability_data(['쓱쓱', '수의베일']),
            hp=85,
            attack=105,
            defense=55,
            sp_attack=85,
            sp_defense=50,
            speed=115,
            level=50
        ),
        PokemonInfo(
            id=407,
            name='로즈레이드',
            types=['풀', '독'],
            moves=move_data(['에너지볼', '오물폭탄', '맹독', '매지컬샤인', '기가드레인', '압정뿌리기', '섀도볼', '씨뿌리기'], ['풀', '독']),
            sex='female',
            ability=ability_data(['독가시', '자연회복']),
            hp=60,
            attack=70,
            defense=65,
            sp_attack=125,
            sp_defense=105,
            speed=90,
            level=50
        ),
        PokemonInfo(
            id=398,
            name='찌르호크',
            types=['노말', '비행'],
            moves=move_data(['인파이트', '브레이브버드', '유턴', '전광석화', '이판사판태클', '애크러뱃', '날개쉬기', '목숨걸기'], ['노말', '비행']),
            ability=ability_data(['위협', '이판사판']),
            hp=85,
            attack=120,
            defense=70,
            sp_attack=50,
            sp_defense=60,
            speed=100,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=405,
            name='렌트라',
            types=['전기'],
            moves=move_data(['썬더다이브', '깨물어부수기', '전기자석파', '개척하기', '치근거리기', '전광석화', '얼음엄니', '불꽃엄니'], ['전기']),
            sex='male',
            ability=ability_data(['위협']),
            hp=80,
            attack=120,
            defense=79,
            sp_attack=95,
            sp_defense=79,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=409,
            name='램펄드',
            types=['바위'],
            moves=move_data(['썬더다이브', '양날박치기', '개척하기', '불꽃펀치', '지진', '겁나는얼굴', '스톤샤워', '아이언헤드', '사념의박치기'], ['바위']),
            sex='male',
            ability=ability_data(['틀깨기', '우격다짐']),
            hp=97,
            attack=165,
            defense=60,
            sp_attack=65,
            sp_defense=50,
            speed=58,
            level=50
        ),
        PokemonInfo(
            id=411,
            name='바리톱스',
            types=['바위', '강철'],
            moves=move_data(['아이언헤드', '땅고르기', '바디프레스', '암석봉인', '메탈버스트', '카운터', '땅가르기', '불대문자', '눈사태', '스텔스록'], ['바위', '강철']),
            sex='male',
            ability=ability_data(['옹골참', '방음']),
            hp=60,
            attack=52,
            defense=168,
            sp_attack=47,
            sp_defense=138,
            speed=30,
            level=50
        ),
        PokemonInfo(
            id=429,
            name='무우마직',
            types=['고스트'],
            moves=move_data(['섀도볼', '나쁜음모', '매지컬샤인', '이상한빛', '얼어붙은바람', '전기자석파', '사이코키네시스', '매지컬플레임', '파워젬', '10만볼트', '에너지볼', '기습'], ['고스트']),
            ability=ability_data(['부유']),
            hp=60,
            attack=60,
            defense=60,
            sp_attack=105,
            sp_defense=105,
            speed=105,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=430,
            name='돈크로우',
            types=['악', '비행'],
            moves=move_data(['깜짝베기', '기습', '애크러뱃', '얼어붙은바람', '유턴', '열풍', '이상한빛', '전기자석파', '사이코키네시스'], ['악', '비행']),
            ability=ability_data(['대운', '자기과신']),
            hp=100,
            attack=125,
            defense=52,
            sp_attack=105,
            sp_defense=52,
            speed=71,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=437,
            name='동탁군',
            types=['강철', '에스퍼'],
            moves=move_data(['신통력', '이상한빛', '헤비봄버', '땅고르기', '풀묶기', '스텔스록', '스톤샤워', '아이스스피너'], ['강철', '에스퍼']),
            ability=ability_data(['부유', '내열']),
            hp=67,
            attack=89,
            defense=116,
            sp_attack=79,
            sp_defense=116,
            speed=33,
            sex=None,
            level=50
        ),
        PokemonInfo(
            id=442,
            name='화강돌',
            types=['악', '고스트'],
            moves=move_data(['이상한빛', '추억의선물', '얼어붙은바람', '암석봉인', '도깨비불', '맹독', '섀도볼', '바크아웃', '사이코키네시스', '아픔나누기'], ['악', '고스트']),
            ability=ability_data(['프레셔']),
            hp=50,
            attack=92,
            defense=108,
            sp_attack=92,
            sp_defense=108,
            speed=35,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=448,
            name='루카리오',
            types=['격투', '강철'],
            moves=move_data(['무릎차기', '파동탄', '코멧펀치', '개척하기', '러스터캐논', '번개펀치', '신속', '악의파동', '독찌르기', '냉동펀치', '칼춤', '불꽃펀치', '스톤샤워', '지진'], ['격투', '강철']),
            ability=ability_data(['정의의마음', '정신력']),
            hp=70,
            attack=110,
            defense=70,
            sp_attack=115,
            sp_defense=70,
            speed=90,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=450,
            name='하마돈',
            types=['땅'],
            moves=move_data(['지진', '암석봉인', '스톤에지', '땅고르기', '바디프레스', '스텔스록', '하품', '땅가르기', '번개엄니', '불꽃엄니', '얼음엄니', '게으름피우기'], ['땅']),
            ability=ability_data(['모래날림']),
            hp=108,
            attack=112,
            defense=118,
            sp_attack=68,
            sp_defense=72,
            speed=47,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=452,
            name='드래피온',
            types=['독', '악'],
            moves=move_data(['크로스포이즌', '깜짝베기', '암석봉인', '마지막일침', '칼춤', '흡혈', '덤벼들기', '지진', '얼음엄니', '번개엄니'], ['독', '악']),
            ability=ability_data(['전투무장', '스나이퍼']),
            hp=70,
            attack=90,
            defense=110,
            sp_attack=60,
            sp_defense=75,
            speed=95,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=454,
            name='독개굴',
            types=['독', '격투'],
            moves=move_data(['드레인펀치', '독찌르기', '냉동펀치', '번개펀치', '기습', '로킥', '더스트슈트', '땅고르기', '맹독', '스톤에지'], ['독', '격투']),
            ability=ability_data(['독수', '건조피부']),
            hp=83,
            attack=106,
            defense=65,
            sp_attack=86,
            sp_defense=65,
            speed=85,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=460,
            name='눈설왕',
            types=['풀', '얼음'],
            moves=move_data(['오로라베일', '기합구슬', '기가드레인', '에너지볼', '얼음뭉치', '눈보라', '얼어붙은바람', '땅고르기', '암석봉인'], ['풀', '얼음']),
            ability=ability_data(['눈퍼뜨리기']),
            hp=90,
            attack=92,
            defense=75,
            sp_attack=92,
            sp_defense=85,
            speed=60,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=461,
            name='포푸니라',
            types=['악', '얼음'],
            moves=move_data(['고드름떨구기', '깜짝베기', '기습', '트리플악셀', '얼음뭉치', '개척하기', '로킥', '속이기'], ['악', '얼음']),
            ability=ability_data(['프레셔']),
            hp=70,
            attack=120,
            defense=65,
            sp_attack=45,
            sp_defense=85,
            speed=125,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=462,
            name='자포코일',
            types=['전기', '강철'],
            moves=move_data(['10만볼트', '러스터캐논', '볼트체인지', '전기자석파', '미러코트', '이상한빛', '일렉트릭네트'], ['전기', '강철']),
            ability=ability_data(['애널라이즈', '옹골참']),
            hp=70,
            attack=70,
            defense=115,
            sp_attack=130,
            sp_defense=90,
            speed=60,
            sex=None,
            level=50
        ),
        PokemonInfo(
            id=464,
            name='거대코뿌리',
            types=['땅', '바위'],
            moves=move_data(['썬더다이브', '스톤샤워', '지진', '땅고르기', '카운터', '암석봉인', '메가혼', '불꽃펀치', '냉동펀치'], ['땅', '바위']),
            ability=ability_data(['하드록', '이판사판']),
            hp=115,
            attack=140,
            defense=130,
            sp_attack=55,
            sp_defense=55,
            speed=40,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=465,
            name='덩쿠림보',
            types=['풀'],
            moves=move_data(['기가드레인', '에너지볼', '씨뿌리기', '방어', '수면가루', '원시의힘', '오물폭탄', '땅고르기', '스톤샤워'], ['풀']),
            ability=ability_data(['엽록소', '재생력']),
            hp=100,
            attack=100,
            defense=125,
            sp_attack=110,
            sp_defense=50,
            speed=50,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=466,
            name='에레키블',
            types=['전기'],
            moves=move_data(['썬더다이브', '불꽃펀치', '냉동펀치', '지진', '깨물어부수기', '개척하기', '일렉트릭네트', '전기자석파', '로킥'], ['전기']),
            ability=ability_data(['전기엔진', '의기양양']),
            hp=75,
            attack=123,
            defense=67,
            sp_attack=95,
            sp_defense=85,
            speed=95,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=468,
            name='토게키스',
            types=['페어리', '비행'],
            moves=move_data(['에어슬래시', '문포스', '원시의힘', '파동탄', '전기자석파', '화염방사', '풀묶기', '트라이어택'], ['페어리', '비행']),
            ability=ability_data(['하늘의은총']),
            hp=85,
            attack=50,
            defense=95,
            sp_attack=120,
            sp_defense=115,
            speed=80,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=469,
            name='메가자리',
            types=['벌레', '비행'],
            moves=move_data(['에어슬래시', '벌레의야단법석', '기가드레인', '섀도볼', '원시의힘', '유턴', '사이코키네시스'], ['벌레', '비행']),
            ability=ability_data(['가속', '색안경']),
            hp=86,
            attack=76,
            defense=86,
            sp_attack=116,
            sp_defense=56,
            speed=95,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=470,
            name='리피아',
            types=['풀'],
            moves=move_data(['리프블레이드', '칼춤', '방어', '씨뿌리기', '개척하기', '구멍파기', '하품', '시저크로스'], ['풀']),
            ability=ability_data(['엽록소', '리프가드']),
            hp=65,
            attack=110,
            defense=130,
            sp_attack=60,
            sp_defense=65,
            speed=95,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=471,
            name='글레이시아',
            types=['얼음'],
            moves=move_data(['냉동빔', '프리즈드라이', '얼어붙은바람', '얼음뭉치', '매혹의보이스', '머드샷', '섀도볼', '하품', '설경'], ['얼음']),
            ability=ability_data(['눈숨기', '아이스바디']),
            hp=65,
            attack=60,
            defense=110,
            sp_attack=130,
            sp_defense=95,
            speed=65,
            sex='female',
            level=50
        ),
        PokemonInfo(
            id=472,
            name='글라이온',
            types=['땅', '비행'],
            moves=move_data(['지진', '독찌르기', '맹독', '칼춤', '스톤샤워', '애크러뱃', '유턴', '깜짝베기', '스케일샷', '독압정', '더블윙'], ['땅', '비행']),
            ability=ability_data(['포이즌힐']),
            hp=75,
            attack=95,
            defense=125,
            sp_attack=45,
            sp_defense=75,
            speed=95,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=473,
            name='맘모꾸리',
            types=['얼음', '땅'],
            moves=move_data(['얼음뭉치', '고드름침', '지진', '땅고르기', '스톤에지', '얼어붙은바람', '개척하기', '아이언헤드', '땅가르기'], ['얼음', '땅']),
            ability=ability_data(['두꺼운지방', '둔감']),
            hp=110,
            attack=130,
            defense=80,
            sp_attack=70,
            sp_defense=60,
            speed=80,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=474,
            name='폴리곤Z',
            types=['노말'],
            moves=move_data(['트라이어택', '섀도볼', '10만볼트', '냉동빔', '기합구슬', '나쁜음모', '사이코키네시스', '파괴광선'], ['노말']),
            ability=ability_data(['다운로드', '적응력']),
            hp=85,
            attack=80,
            defense=70,
            sp_attack=135,
            sp_defense=75,
            speed=90,
            sex=None,
            level=50
        ),
        PokemonInfo(
            id=475,
            name='엘레이드',
            types=['에스퍼', '격투'],
            moves=move_data(['성스러운칼', '사이코커터', '야습', '고속이동', '리프블레이드', '칼춤', '깜짝베기', '아쿠아커터'], ['격투', '에스퍼']),
            ability=ability_data(['예리함', '정의의마음']),
            hp=68,
            attack=125,
            defense=65,
            sp_attack=65,
            sp_defense=115,
            speed=80,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=476,
            name='대코파스',
            types=['바위', '강철'],
            moves=move_data(['스텔스록', '스톤샤워', '전기자석파', '러스터캐논', '10만볼트', '땅고르기', '바디프레스', '대지의힘'], ['바위', '강철']),
            ability=ability_data(['옹골참']),
            hp=60,
            attack=55,
            defense=145,
            sp_attack=75,
            sp_defense=150,
            speed=40,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=477,
            name='야느와르몽',
            types=['고스트'],
            moves=move_data(['폴터가이스트', '불꽃펀치', '냉동펀치', '도깨비불', '이상한빛', '아픔나누기', '추억의선물', '흡혈', '번개펀치', '방어'], ['고스트']),
            ability=ability_data(['프레셔']),
            hp=45,
            attack=100,
            defense=135,
            sp_attack=65,
            sp_defense=135,
            speed=45,
            sex='male',
            level=50
        ),
        PokemonInfo(
            id=637,
            name='불카모스',
            types=['벌레', '불'],
            moves=move_data(['불대문자', '폭풍', '불꽃춤', '벌레의야단법석', '기가드레인', '개척하기', '사이코키네시스', '에어슬래시', '나비춤', '아침햇살'], ['벌레', '불']),
            sex='female',
            ability=ability_data(['벌레의알림', '불꽃몸']),
            hp=85,
            attack=60,
            defense=65,
            sp_attack=135,
            sp_defense=105,
            speed=100,
            level=50
        ),
        PokemonInfo(
            id=537,
            name='두빅굴',
            types=['물', '땅'],
            moves=move_data(['하이드로펌프', '지진', '아쿠아브레이크', '냉동펀치', '독찌르기', '스톤에지', '파워휩', '스텔스록'], ['물', '땅']),
            sex='male',
            ability=ability_data(['저수', '독수']),
            hp=105,
            attack=95,
            defense=75,
            sp_attack=85,
            sp_defense=75,
            speed=74,
            level=50
        ),
        PokemonInfo(
            id=542,
            name='모아머',
            types=['벌레', '풀'],
            moves=move_data(['마지막일침', '리프블레이드', '덤벼들기', '개척하기', '섀도클로', '독찌르기', '트리플악셀', '칼춤'], ['벌레', '풀']),
            sex='female',
            ability=ability_data(['벌레의알림', '엽록소']),
            hp=75,
            attack=103,
            defense=80,
            sp_attack=70,
            sp_defense=80,
            speed=92,
            level=50
        ),
        PokemonInfo(
            id=508,
            name='바랜드',
            types=['노말'],
            moves=move_data(['치근거리기', '깨물어부수기', '기가임팩트', '암석봉인', '와일드볼트', '아이언헤드', '하품'], ['노말']),
            sex='male',
            ability=ability_data(['위협', '배짱']),
            hp=85,
            attack=110,
            defense=90,
            sp_attack=45,
            sp_defense=90,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=523,
            name='제브라이카',
            types=['전기'],
            moves=move_data(['니트로차지', '전기자석파', '개척하기', '10만마력', '썬더다이브', '볼트체인지'], ['전기']),
            sex='male',
            ability=ability_data(['전기엔진', '초식']),
            hp=75,
            attack=100,
            defense=63,
            sp_attack=80,
            sp_defense=63,
            speed=116,
            level=50
        ),
        PokemonInfo(
            id=526,
            name='기가이어스',
            types=['바위'],
            moves=move_data(['스톤에지', '지진', '대폭발', '스텔스록', '암석봉인', '바디프레스', '철벽', '땅고르기'], ['바위']),
            sex='male',
            ability=ability_data(['옹골참', '모래날림']),
            hp=85,
            attack=135,
            defense=130,
            sp_attack=60,
            sp_defense=80,
            speed=25,
            level=50
        ),
        PokemonInfo(
            id=530,
            name='몰드류',
            types=['땅', '강철'],
            moves=move_data(['지진', '아이언헤드', '스톤에지', '칼춤', '암석봉인', '독찌르기', '지옥찌르기', '모래바람'], ['땅']),
            sex='male',
            ability=ability_data(['모래헤치기', '틀깨기']),
            hp=110,
            attack=135,
            defense=60,
            sp_attack=50,
            sp_defense=65,
            speed=88,
            level=50
        ),
        PokemonInfo(
            id=534,
            name='노보청',
            types=['격투'],
            moves=move_data(['스톤샤워', '불꽃펀치', '냉동펀치', '로킥', '번개펀치', '드레인펀치', '마하펀치'], ['격투']),
            sex='male',
            ability=ability_data(['철주먹', '우격다짐']),
            hp=105,
            attack=145,
            defense=95,
            sp_attack=55,
            sp_defense=65,
            speed=45,
            level=50
        ),
        PokemonInfo(
            id=545,
            name='펜드라',
            types=['벌레', '독'],
            moves=move_data(['독찌르기', '메가혼', '압정뿌리기', '방어', '땅고르기', '독압정', '스톤샤워'], ['벌레']),
            sex='male',
            ability=ability_data(['가속', '독가시', '벌레의알림']),
            hp=60,
            attack=100,
            defense=89,
            sp_attack=55,
            sp_defense=69,
            speed=112,
            level=50
        ),
        PokemonInfo(
            id=553,
            name='악비아르',
            types=['악', '땅'],
            moves=move_data(['깨물어부수기', '지진', '스톤에지', '더스트슈트', '인파이트', '아쿠아테일', '땅고르기'], ['악', '땅']),
            sex='male',
            ability=ability_data(['위협', '자기과신']),
            hp=95,
            attack=117,
            defense=80,
            sp_attack=65,
            sp_defense=70,
            speed=92,
            level=50
        ),
        PokemonInfo(
            id=555,
            name='불비달마',
            types=['불'],
            moves=move_data(['플레어드라이브', '지진', '스톤샤워', '유턴', '엄청난힘', '아이언헤드'], ['불']),
            sex='male',
            ability=ability_data(['우격다짐']),
            hp=105,
            attack=140,
            defense=55,
            sp_attack=30,
            sp_defense=55,
            speed=95,
            level=50
        ),
        PokemonInfo(
            id=560,
            name='곤율거니',
            types=['악', '격투'],
            moves=move_data(['무릎차기', '양날박치기', '로킥', '깨물어부수기', '속이기', '용의춤', '독찌르기', '번개펀치'], ['악', '격투']),
            sex='female',
            ability=ability_data(['위협', '자기과신']),
            hp=65,
            attack=95,
            defense=115,
            sp_attack=45,
            sp_defense=115,
            speed=58,
            level=50
        ),
        PokemonInfo(
            id=561,
            name='심보러',
            types=['에스퍼', '비행'],
            moves=move_data(['사이코키네시스', '악의파동', '열풍', '에어슬래시', '코스믹파워', '전기자석파', '얼어붙은바람', '에너지볼', '러스터캐논'], ['에스퍼', '비행']),
            sex='male',
            ability=ability_data(['미라클스킨', '색안경', '매직가드']),
            hp=72,
            attack=58,
            defense=80,
            sp_attack=103,
            sp_defense=80,
            speed=97,
            level=50
        ),
        PokemonInfo(
            id=565,
            name='늑골라',
            types=['물', '바위'],
            moves=move_data(['지진', '깨물어부수기', '스톤에지', '아쿠아제트', '껍질깨기', '암석봉인', '아쿠아브레이크', '엄청난힘', '얼어붙은바람'], ['물', '바위']),
            sex='male',
            ability=ability_data(['하드록', '옹골참']),
            hp=74,
            attack=108,
            defense=133,
            sp_attack=83,
            sp_defense=65,
            speed=32,
            level=50
        ),
        PokemonInfo(
            id=567,
            name='아케오스',
            types=['바위', '비행'],
            moves=move_data(['스톤에지', '유턴', '드래곤클로', '애크러뱃', '양날박치기', '지진', '사념의박치기', '열풍'], ['바위', '비행']),
            sex='male',
            ability=ability_data(['무기력']),
            hp=75,
            attack=140,
            defense=65,
            sp_attack=112,
            sp_defense=65,
            speed=110,
            level=50
        ),
        PokemonInfo(
            id=584,
            name='배바닐라',
            types=['얼음'],
            moves=move_data(['프리즈드라이', '얼음뭉치', '눈보라', '얼어붙은바람', '러스터캐논', '오로라베일', '절대영도'], ['얼음']),
            sex='female',
            ability=ability_data(['눈퍼뜨리기', '깨어진갑옷']),
            hp=71,
            attack=95,
            defense=85,
            sp_attack=110,
            sp_defense=95,
            speed=79,
            level=50
        ),
        PokemonInfo(
            id=596,
            name='전툴라',
            types=['벌레', '전기'],
            moves=move_data(['벌레의야단법석', '10만볼트', '기가드레인', '전기자석파', '끈적끈적네트', '기습', '일렉트릭네트'], ['벌레', '전기']),
            sex='female',
            ability=ability_data(['복안', '벌레의알림']),
            hp=70,
            attack=77,
            defense=60,
            sp_attack=97,
            sp_defense=60,
            speed=108,
            level=50
        ),
        PokemonInfo(
            id=601,
            name='기기기어르',
            types=['강철'],
            moves=move_data(['기어체인지', '와일드볼트', '기어소서', '전기자석파', '볼트체인지', '싫은소리'], ['강철']),
            sex=None,
            ability=ability_data(['클리어바디']),
            hp=60,
            attack=100,
            defense=115,
            sp_attack=70,
            sp_defense=85,
            speed=90,
            level=50
        ),
        PokemonInfo(
            id=604,
            name='저리더프',
            types=['전기'],
            moves=move_data(['썬더다이브', '불꽃펀치', '아쿠아브레이크', '기가드레인', '애크러뱃', '유턴', '드레인펀치', '전기자석파'], ['전기']),
            sex='male',
            ability=ability_data(['부유']),
            hp=85,
            attack=115,
            defense=80,
            sp_attack=105,
            sp_defense=80,
            speed=50,
            level=50
        ),
        PokemonInfo(
            id=609,
            name='샹델라',
            types=['고스트', '불'],
            moves=move_data(['섀도볼', '열풍', '에너지볼', '사이코키네시스', '도깨비불', '아픔나누기', '이상한빛', '오버히트', '니트로차지'], ['고스트', '불']),
            sex='female',
            ability=ability_data(['타오르는불꽃', '불꽃몸']),
            hp=60,
            attack=55,
            defense=90,
            sp_attack=145,
            sp_defense=90,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=612,
            name='액스라이즈',
            types=['드래곤'],
            moves=move_data(['용의춤', '지진', '스톤에지', '깨물어부수기', '드래곤클로', '개척하기', '독찌르기', '스케일샷', '만나자마자', '인파이트', '역린'], ['드래곤']),
            sex='male',
            ability=ability_data(['틀깨기']),
            hp=76,
            attack=147,
            defense=90,
            sp_attack=60,
            sp_defense=70,
            speed=97,
            level=50
        ),
        PokemonInfo(
            id=614,
            name='툰베어',
            types=['얼음'],
            moves=move_data(['고드름떨구기', '아쿠아제트', '설경', '치근거리기', '아쿠아브레이크', '인파이트', '개척하기'], ['얼음']),
            sex='male',
            ability=ability_data(['눈숨기', '눈치우기']),
            hp=95,
            attack=130,
            defense=80,
            sp_attack=70,
            sp_defense=80,
            speed=50,
            level=50
        ),
        PokemonInfo(
            id=620,
            name='비조도',
            types=['격투'],
            moves=move_data(['속이기', '유턴', '무릎차기', '애크러뱃', '개척하기', '트리플악셀', '독찌르기', '스톤에지', '구멍파기'], ['격투']),
            sex='male',
            ability=ability_data(['정신력', '재생력', '이판사판']),
            hp=65,
            attack=125,
            defense=60,
            sp_attack=95,
            sp_defense=60,
            speed=105,
            level=50
        ),
        PokemonInfo(
            id=623,
            name='골루그',
            types=['땅', '고스트'],
            moves=move_data(['지진', '섀도펀치', '냉동펀치', '폭발펀치', '번개펀치', '불꽃펀치', '공중날기', '암석봉인'], ['고스트']),
            sex='male',
            ability=ability_data(['철주먹', '노가드']),
            hp=89,
            attack=124,
            defense=80,
            sp_attack=55,
            sp_defense=80,
            speed=55,
            level=50
        ),
        PokemonInfo(
            id=628,
            name='워글',
            types=['노말', '비행'],
            moves=move_data(['브레이브버드', '애크러뱃', '브레이크클로', '유턴', '아이언헤드', '스톤샤워', '이판사판태클', '섀도클로', '고속이동'], ['노말', '비행']),
            sex='male',
            ability=ability_data(['오기', '우격다짐']),
            hp=100,
            attack=123,
            defense=75,
            sp_attack=57,
            sp_defense=75,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=630,
            name='버랜지나',
            types=['악', '비행'],
            moves=move_data(['맹독', '부추기기', '속임수', '날개쉬기', '유턴', '공중날기', '철벽'], ['악', '비행']),
            sex='female',
            ability=ability_data(['방진', '부풀린가슴']),
            hp=110,
            attack=65,
            defense=105,
            sp_attack=55,
            sp_defense=95,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=663,
            name='파이어로',
            types=['불', '비행'],
            moves=move_data(['브레이브버드', '플레어드라이브', '애크러뱃', '유턴', '칼춤', '전광석화', '날개쉬기', '도깨비불', '열불내기'], ['불', '비행']),
            sex='male',
            ability=ability_data(['불꽃몸', '질풍날개']),
            hp=78,
            attack=81,
            defense=71,
            sp_attack=74,
            sp_defense=69,
            speed=126,
            level=50
        ),
        PokemonInfo(
            id=693,
            name='블로스터',
            types=['물'],
            moves=move_data(['물의파동', '러스터캐논', '악의파동', '용의파동', '파동탄', '냉동빔', '퀵턴', '얼어붙은바람'], ['물']),
            sex='male',
            ability=ability_data(['메가런처']),
            hp=71,
            attack=73,
            defense=88,
            sp_attack=120,
            sp_defense=89,
            speed=59,
            level=50
        ),
        PokemonInfo(
            id=711,
            name='펌킨인',
            types=['고스트', '풀'],
            moves=move_data(['고스트다이브', '씨폭탄', '스톤샤워', '야습', '도깨비불', '파워휩', '트릭룸', '폴터가이스트', '불대문자'], ['고스트', '풀']),
            sex='female',
            ability=ability_data(['불면']),
            hp=65,
            attack=90,
            defense=122,
            sp_attack=58,
            sp_defense=75,
            speed=84,
            level=50
        ),
        PokemonInfo(
            id=671,
            name='플라제스',
            types=['페어리'],
            moves=move_data(['문포스', '에너지볼', '에너지볼', '광합성', '드레인키스', '사이코키네시스', '꽃가루경단', '명상'], ['페어리']),
            sex='female',
            ability=ability_data(['플라워베일']),
            hp=78,
            attack=65,
            defense=68,
            sp_attack=112,
            sp_defense=154,
            speed=75,
            level=50
        ),
        PokemonInfo(
            id=678,
            name='냐오닉스',
            types=['에스퍼'],
            moves=move_data(['사이코키네시스', '섀도볼', '매지컬샤인', '에너지볼', '전기자석파', '리플렉터', '빛의장막', '하품'], ['에스퍼']),
            sex='male',
            ability=ability_data(['짓궂은마음']),
            hp=74,
            attack=48,
            defense=76,
            sp_attack=83,
            sp_defense=81,
            speed=104,
            level=50
        ),
        PokemonInfo(
            id=691,
            name='드래캄',
            types=['독', '드래곤'],
            moves=move_data(['용의파동', '오물폭탄', '하이드로펌프', '용성군', '10만볼트', '맹독', '스케일샷', '파도타기'], ['드래곤', '독']),
            sex='female',
            ability=ability_data(['적응력', '독가시']),
            hp=65,
            attack=75,
            defense=90,
            sp_attack=97,
            sp_defense=123,
            speed=44,
            level=50
        ),
        PokemonInfo(
            id=695,
            name='일레도리자드',
            types=['전기', '노말'],
            moves=move_data(['10만볼트', '볼트체인지', '파라볼라차지', '암석봉인', '파도타기', '풀묶기', '용의파동', '파괴광선', '스케일샷', '뱀눈초리'], ['전기', '노말']),
            sex='male',
            ability=ability_data(['건조피부', '모래숨기', '선파워']),
            hp=62,
            attack=55,
            defense=52,
            sp_attack=109,
            sp_defense=94,
            speed=109,
            level=50
        ),
        PokemonInfo(
            id=697,
            name='견고라스',
            types=['바위', '드래곤'],
            moves=move_data(['스톤에지', '양날박치기', '지진', '깨물어부수기', '번개엄니', '얼음엄니', '불꽃엄니', '용의춤', '치근거리기', '사이코팽', '스케일샷', '역린'], ['바위', '드래곤']),
            sex='male',
            ability=ability_data(['옹골찬턱', '돌머리']),
            hp=82,
            attack=121,
            defense=119,
            sp_attack=69,
            sp_defense=59,
            speed=71,
            level=50
        ),
        PokemonInfo(
            id=699,
            name='아마루르가',
            types=['바위', '얼음'],
            moves=move_data(['프리즈드라이', '원시의힘', '문포스', '오로라베일', '눈보라', '파괴광선', '전기자석파', '사이코키네시스'], ['얼음', '바위']),
            sex='female',
            ability=ability_data(['프리즈스킨', '눈퍼뜨리기']),
            hp=123,
            attack=77,
            defense=72,
            sp_attack=99,
            sp_defense=92,
            speed=58,
            level=50
        ),
        PokemonInfo(
            id=700,
            name='님피아',
            types=['페어리'],
            moves=move_data(['문포스', '하이퍼보이스', '매지컬플레임', '사이코쇼크', '명상', '파괴광선', '하품'], ['페어리', '노말']),
            sex='female',
            ability=ability_data(['페어리스킨']),
            hp=95,
            attack=65,
            defense=65,
            sp_attack=110,
            sp_defense=130,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=701,
            name='루차불',
            types=['격투', '비행'],
            moves=move_data(['플라잉프레스', '스톤에지', '무릎차기', '애크러뱃', '칼춤', '개척하기', '유턴', '번개펀치'], ['격투', '비행']),
            sex='male',
            ability=ability_data(['곡예', '틀깨기']),
            hp=78,
            attack=92,
            defense=75,
            sp_attack=74,
            sp_defense=63,
            speed=118,
            level=50
        ),
        PokemonInfo(
            id=713,
            name='크레베이스',
            types=['얼음'],
            moves=move_data(['눈사태', '스톤에지', '지진', 'HP회복', '철벽', '아이언헤드', '바디프레스', '미러코트', '얼어붙은바람'], ['얼음']),
            sex='female',
            ability=ability_data(['옹골참', '마이페이스']),
            hp=95,
            attack=117,
            defense=184,
            sp_attack=44,
            sp_defense=46,
            speed=28,
            level=50
        ),
        PokemonInfo(
            id=715,
            name='음번',
            types=['비행', '드래곤'],
            moves=move_data(['폭음파', '용성군', '화염방사', '에어슬래시', '폭풍', '기습', '유턴', '사이코키네시스', '악의파동'], ['드래곤', '비행', '노말']),
            sex='male',
            ability=ability_data(['틈새포착']),
            hp=85,
            attack=70,
            defense=80,
            sp_attack=97,
            sp_defense=80,
            speed=123,
            level=50
        ),
        PokemonInfo(
            id=758,
            name='염뉴트',
            types=['불', '독'],
            moves=move_data(['화염방사', '맹독', '도깨비불', '애시드봄', '섀도볼', '오물폭탄', '전기자석파', '개척하기', '불대문자'], ['불', '독']),
            sex='female',
            ability=ability_data(['부식', '둔감']),
            hp=68,
            attack=64,
            defense=60,
            sp_attack=111,
            sp_defense=60,
            speed=117,
            level=50
        ),
        PokemonInfo(
            id=752,
            name='깨비물거미',
            types=['물', '벌레'],
            moves=move_data(['아쿠아브레이크', '흡혈', '덤벼들기', '독찌르기', '개척하기', '기가드레인', '폭포오르기'], ['물', '벌레']),
            sex='male',
            ability=ability_data(['수포', '저수']),
            hp=68,
            attack=70,
            defense=92,
            sp_attack=50,
            sp_defense=132,
            speed=42,
            level=50
        ),
        PokemonInfo(
            id=763,
            name='달코퀸',
            types=['풀'],
            moves=move_data(['트로피컬킥', '유턴', '씨폭탄', '무릎차기', '개척하기', '애크러뱃', '로킥', '트리플악셀'], ['풀']),
            sex='female',
            ability=ability_data(['여왕의위엄', '리프가드']),
            hp=72,
            attack=120,
            defense=98,
            sp_attack=50,
            sp_defense=98,
            speed=72,
            level=50
        ),
        PokemonInfo(
            id=738,
            name='투구뿌논',
            types=['벌레', '전기'],
            moves=move_data(['10만볼트', '볼트체인지', '에어슬래시', '전기자석파', '에너지볼', '벌레의야단법석', '일렉트릭네트', '러스터캐논'], ['벌레', '전기']),
            sex='male',
            ability=ability_data(['부유']),
            hp=77,
            attack=70,
            defense=90,
            sp_attack=145,
            sp_defense=75,
            speed=43,
            level=50
        ),
        PokemonInfo(
            id=745,
            name='루가루암',
            types=['바위'],
            moves=move_data(['스톤에지', '액셀록', '깨트리기', '기습', '인파이트', '아이언헤드', '개척하기', '암석봉인', '사이코팽', '치근거리기', '드릴라이너'], ['바위']),
            sex='male',
            ability=ability_data(['단단한발톱']),
            hp=75,
            attack=117,
            defense=65,
            sp_attack=55,
            sp_defense=65,
            speed=110,
            level=50
        ),
        PokemonInfo(
            id=746,
            name='약어리',
            types=['물'],
            moves=move_data(['아쿠아브레이크', '지진', '퀵턴', '잠자기', '스케일샷', '하이드로펌프', '냉동빔', '아이언테일'], ['물']),
            sex='male',
            ability=ability_data(['어군']),
            hp=45,
            attack=140,
            defense=130,
            sp_attack=140,
            sp_defense=135,
            speed=30,
            level=50,
            has_form_change=True,
        ),
        PokemonInfo(
            id=748,
            name='더시마사리',
            types=['물', '독'],
            moves=move_data(['독압정', 'HP회복', '토치카', '찬물끼얹기', '얼어붙은바람', '머드샷', '아픔나누기', '독찌르기'], ['물', '독']),
            sex='male',
            ability=ability_data(['재생력']),
            hp=50,
            attack=63,
            defense=152,
            sp_attack=53,
            sp_defense=142,
            speed=35,
            level=50
        ),
        PokemonInfo(
            id=750,
            name='만마드',
            types=['땅'],
            moves=move_data(['지진', '암석봉인', '땅고르기', '스톤에지', '땅가르기', '바디프레스', '아이언헤드', '철벽'], ['땅']),
            sex='male',
            ability=ability_data(['지구력', '마이페이스']),
            hp=100,
            attack=125,
            defense=100,
            sp_attack=55,
            sp_defense=85,
            speed=35,
            level=50
        ),
        PokemonInfo(
            id=754,
            name='라란티스',
            types=['풀'],
            moves=move_data(['리프블레이드', '흡혈', '리프스톰', '엄청난힘', '독찌르기', '로킥', '깜짝베기'], ['풀']),
            sex='female',
            ability=ability_data(['리프가드', '심술꾸러기']),
            hp=70,
            attack=105,
            defense=90,
            sp_attack=80,
            sp_defense=90,
            speed=45,
            level=50
        ),
        PokemonInfo(
            id=764,
            name='큐아링',
            types=['페어리'],
            moves=move_data(['드레인키스', '기가드레인', '명상', '씨뿌리기', '애교부리기', '광합성'], ['페어리']),
            sex='female',
            ability=ability_data(['힐링시프트', '자연회복']),
            hp=51,
            attack=52,
            defense=90,
            sp_attack=82,
            sp_defense=110,
            speed=100,
            level=50
        ),
        PokemonInfo(
            id=768,
            name='갑주무사',
            types=['벌레', '물'],
            moves=move_data(['만나자마자', '아쿠아브레이크', '기습', '칼춤', '암석봉인', '흡혈', '인파이트', '독찌르기', '드릴라이너', '아쿠아제트'], ['벌레', '물']),
            sex='male',
            ability=ability_data(['위기회피']),
            hp=75,
            attack=125,
            defense=140,
            sp_attack=60,
            sp_defense=90,
            speed=40,
            level=50
        ),
        PokemonInfo(
            id=773,
            name='실버디',
            types=['노말'],
            moves=move_data(['아이언헤드', '독찌르기', '멀티어택', '냉동빔', '막말내뱉기', '화염방사', '파도타기', '10만볼트', '칼춤', '유턴'], ['노말']),
            sex='male',
            ability=ability_data(['AR시스템']),
            hp=95,
            attack=95,
            defense=95,
            sp_attack=95,
            sp_defense=95,
            speed=95,
            level=50
        ),
        PokemonInfo(
            id=781,
            name='타타륜',
            types=['풀', '고스트'],
            moves=move_data(['앵커샷', '지진', '고스트다이브', '파워휩', '아이언헤드', '폴터가이스트', '아쿠아브레이크', '깨트리기', '기가드레인', '스톤에지'], ['풀', '고스트']),
            sex='male',
            ability=ability_data(['강철술사']),
            hp=70,
            attack=131,
            defense=100,
            sp_attack=86,
            sp_defense=90,
            speed=40,
            level=50
        ),
        PokemonInfo(
            id=839,
            name='석탄산',
            types=['바위', '불'],
            moves=move_data(['스톤에지', '화염방사', '암석봉인', '열탕', '대폭발', '스텔스록', '지진', '플레어드라이브'], ['바위', '불']),
            sex='male',
            ability=ability_data(['증기기관']),
            hp=110,
            attack=80,
            defense=120,
            sp_attack=80,
            sp_defense=90,
            speed=30,
            level=50
        ),
        PokemonInfo(
            id=823,
            name='아머까오',
            types=['비행', '강철'],
            moves=move_data(['아이언헤드', '공중날기', '벌크업', '날개쉬기', '바디프레스', '제비반환'], ['강철', '비행']),
            sex='male',
            ability=ability_data(['프레셔', '미러아머']),
            hp=98,
            attack=87,
            defense=105,
            sp_attack=53,
            sp_defense=85,
            speed=67,
            level=50
        ),
        PokemonInfo(
            id=826,
            name='이올브',
            types=['벌레', '에스퍼'],
            moves=move_data(['사이코키네시스', '벌레의야단법석', '이상한빛', '미러코트', '에너지볼', '바디프레스', '끈적끈적네트'], ['에스퍼', '벌레']),
            sex='female',
            ability=ability_data(['벌레의알림']),
            hp=60,
            attack=45,
            defense=110,
            sp_attack=80,
            sp_defense=120,
            speed=90,
            level=50
        ),
        PokemonInfo(
            id=834,
            name='갈가부기',
            types=['물', '바위'],
            moves=move_data(['비바라기', '깨물어부수기', '양날박치기', '아쿠아브레이크', '얼음엄니', '독찌르기', '껍질깨기', '지진', '스톤에지'], ['물', '바위']),
            sex='male',
            ability=ability_data(['옹골찬턱', '쓱쓱']),
            hp=90,
            attack=115,
            defense=90,
            sp_attack=48,
            sp_defense=68,
            speed=74,
            level=50
        ),
        PokemonInfo(
            id=836,
            name='펄스멍',
            types=['전기'],
            moves=move_data(['10만볼트', '사이코팽', '불꽃엄니', '볼부비부비', '볼트체인지', '치근거리기', '깨물어부수기'], ['전기']),
            sex='female',
            ability=ability_data(['옹골찬턱', '승기']),
            hp=69,
            attack=90,
            defense=60,
            sp_attack=90,
            sp_defense=60,
            speed=121,
            level=50
        ),
        PokemonInfo(
            id=844,
            name='사다이사',
            types=['땅'],
            moves=move_data(['모래지옥', '지진', '스톤샤워', '뱀눈초리', '똬리틀기', '바디프레스', '번개엄니', '스텔스록'], ['땅']),
            sex='male',
            ability=ability_data(['모래뿜기', '탈피']),
            hp=72,
            attack=107,
            defense=125,
            sp_attack=65,
            sp_defense=70,
            speed=71,
            level=50
        ),
        PokemonInfo(
            id=847,
            name='꼬치조',
            types=['물'],
            moves=move_data(['아쿠아제트', '아쿠아브레이크', '깨물어부수기', '깨트리기', '사이코팽', '독찌르기', '드릴라이너', '인파이트', '스케일샷'], ['물']),
            sex='male',
            ability=ability_data(['쓱쓱']),
            hp=61,
            attack=123,
            defense=60,
            sp_attack=60,
            sp_defense=50,
            speed=136,
            level=50
        ),
        PokemonInfo(
            id=849,
            name='스트린더',
            types=['전기', '독'],
            moves=move_data(['오물웨이브', '일렉트릭네트', '볼트체인지', '폭음파', '오버드라이브', '개척하기', '애시드봄', '볼부비부비'], ['전기', '독']),
            sex='male',
            ability=ability_data(['펑크록', '테크니션']),
            hp=75,
            attack=98,
            defense=70,
            sp_attack=114,
            sp_defense=70,
            speed=75,
            level=50
        ),
        PokemonInfo(
            id=851,
            name='다태우지네',
            types=['벌레', '불꽃'],
            moves=move_data(['흡혈', '오버히트', '덤벼들기', '열탕', '불꽃채찍', '파워휩', '깨물어부수기'], ['벌레', '불꽃']),
            sex='female',
            ability=ability_data(['하얀연기', '불꽃몸', '타오르는불꽃']),
            hp=100,
            attack=115,
            defense=65,
            sp_attack=90,
            sp_defense=90,
            speed=65,
            level=50
        ),
        PokemonInfo(
            id=855,
            name='포트데스',
            types=['고스트'],
            moves=move_data(['섀도볼', '껍질깨기', '힘흡수', '나쁜음모', '기가드레인', '기습', '사이코키네시스', '배턴터치'], ['고스트']),
            sex='female',
            ability=ability_data(['깨어진갑옷', '저주받은바디']),
            hp=60,
            attack=65,
            defense=65,
            sp_attack=134,
            sp_defense=114,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=858,
            name='브리무음',
            types=['에스퍼', '페어리'],
            moves=move_data(['사이코키네시스', '매지컬샤인', '트릭룸', '명상', '마법가루', '드레인키스', '볼부비부비', '기가드레인', '매지컬플레임', '악의파동'], ['에스퍼', '페어리']),
            sex='female',
            ability=ability_data(['매직미러']),
            hp=57,
            attack=90,
            defense=95,
            sp_attack=136,
            sp_defense=103,
            speed=29,
            level=50
        ),
        PokemonInfo(
            id=861,
            name='오롱털',
            types=['악', '페어리'],
            moves=move_data(['속임수', '기습', '소울크래시', '부추기기', '드레인펀치', '전기자석파', '막말내뱉기', '리플렉터', '빛의장막', '로킥'], ['악', '페어리']),
            sex='male',
            ability=ability_data(['짓궂은마음']),
            hp=95,
            attack=120,
            defense=65,
            sp_attack=95,
            sp_defense=75,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=862,
            name='가로막구리',
            types=['악', '노말'],
            moves=move_data(['블로킹', '기습', '인파이트', '전기자석파', '깨물어부수기', '씨폭탄', '더스트슈트', '누르기'], ['악', '노말']),
            sex='male',
            ability=ability_data(['이판사판', '오기']),
            hp=93,
            attack=90,
            defense=101,
            sp_attack=60,
            sp_defense=81,
            speed=95,
            level=50
        ),
        PokemonInfo(
            id=864,
            name='산호르곤',
            types=['고스트'],
            moves=move_data(['파워젬', '미러코트', '얼어붙은바람', '섀도볼', '기가드레인', '힘흡수', '파도타기', '길동무'], ['고스트']),
            sex='female',
            ability=ability_data(['깨어진갑옷']),
            hp=60,
            attack=95,
            defense=50,
            sp_attack=145,
            sp_defense=130,
            speed=30,
            level=50
        ),
        PokemonInfo(
            id=865,
            name='창파나이트',
            types=['격투'],
            moves=move_data(['인파이트', '리프블레이드', '만나자마자', '스타어설트', '칼춤', '브레이브버드', '깜짝베기'], ['격투']),
            sex='male',
            ability=ability_data(['배짱']),
            hp=62,
            attack=135,
            defense=95,
            sp_attack=68,
            sp_defense=82,
            speed=65,
            level=50
        ),
        PokemonInfo(
            id=911,
            name='라우드본',
            types=['불', '고스트'],
            moves=move_data(['플레어송', '게으름피우기', '섀도볼', '도깨비불', '오버히트', '대지의힘', '씨폭탄', '매혹의보이스'], ['불', '고스트']),
            sex='male',
            ability=ability_data(['맹화', '천진']),
            hp=104,
            attack=75,
            defense=100,
            sp_attack=110,
            sp_defense=75,
            speed=66,
            level=50
        ),
        PokemonInfo(
            id=908,
            name='마스카나',
            types=['풀', '악'],
            moves=move_data(['트릭플라워', '유턴', '깜짝베기', '치근거리기', '애크러뱃', '개척하기', '로킥', '트리플악셀', '찬물끼얹기'], ['풀', '악']),
            sex='female',
            ability=ability_data(['변환자재', '심록']),
            hp=76,
            attack=110,
            defense=70,
            sp_attack=81,
            sp_defense=70,
            speed=123,
            level=50
        ),
        PokemonInfo(
            id=914,
            name='웨이니발',
            types=['물', '격투'],
            moves=move_data(['아쿠아스텝', '웨이브태클', '인파이트', '브레이브버드', '아쿠아브레이크', '트리플악셀', '로킥', '유턴'], ['물', '격투']),
            sex='male',
            ability=ability_data(['자기과신', '급류']),
            hp=85,
            attack=120,
            defense=80,
            sp_attack=85,
            sp_defense=75,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=937,
            name='파라블레이즈',
            types=['불', '고스트'],
            moves=move_data(['원념의칼', '야습', '니트로차지', '폴터가이스트', '아이언헤드', '이상한빛', '인파이트', '독찌르기'], ['불', '고스트']),
            sex='male',
            ability=ability_data(['깨어진갑옷']),
            hp=75,
            attack=125,
            defense=80,
            sp_attack=60,
            sp_defense=100,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=977,
            name='어써러셔',
            types=['물'],
            moves=move_data(['웨이브태클', '아쿠아브레이크', '헤비봄버', '눈사태', '땅가르기', '바디프레스', '스톤샤워', '지진'], ['물']),
            sex='male',
            ability=ability_data(['천진', '수의베일']),
            hp=150,
            attack=100,
            defense=115,
            sp_attack=65,
            sp_defense=65,
            speed=35,
            level=50
        ),
        PokemonInfo(
            id=952,
            name='스코빌런',
            types=['풀', '불'],
            moves=move_data(['기가드레인', '불대문자', '개척하기', '오버히트', '깨물어부수기', '분함의발구르기', '방어'], ['풀', '불']),
            sex='male',
            ability=ability_data(['변덕쟁이', '엽록소']),
            hp=65,
            attack=108,
            defense=65,
            sp_attack=108,
            sp_defense=65,
            speed=75,
            level=50
        )
    ]