# env/mock_pokemon.py
from typing import List
from p_models.pokemon_info import PokemonInfo
from p_data.move_data import move_data
from p_data.ability_data import ability_data

def create_mock_pokemon_list() -> List[PokemonInfo]:
    return [
        PokemonInfo(
            id=3,
            name='이상해꽃',
            types=['풀', '독'],
            moves=move_data(['대지의힘', '씨뿌리기', '광합성', '쾌청', '기가드레인', '오물폭탄', '수면가루', '맹독', '에너지볼'], ['풀', '독']),
            sex='male',
            ability=ability_data(['엽록소', '심록']),
            hp=80,
            attack=82,
            sp_attack=100,
            defense=83,
            sp_defense=100,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=6,
            name='리자몽',
            types=['불', '비행'],
            moves=move_data(['에어슬래시', '불대문자', '오버히트', '지진', '니트로차지', '화염방사', '폭풍', '용의파동', '원시의힘'], ['불', '비행']),
            sex='male',
            ability=ability_data(['맹화', '선파워']),
            hp=78,
            attack=84,
            sp_attack=109,
            defense=78,
            sp_defense=85,
            speed=100,
            level=50
        ),
        PokemonInfo(
            id=9,
            name='거북왕',
            types=['물'],
            moves=move_data(['껍질깨기', '하이드로펌프', '냉동빔', '악의파동', '아쿠아제트', '퀵턴', '파동탄', '러스터캐논', '지진'], ['물']),
            sex='male',
            ability=ability_data(['급류']),
            hp=79,
            attack=83,
            sp_attack=85,
            defense=100,
            sp_defense=105,
            speed=78,
            level=50
        ),
        PokemonInfo(
            id=157,
            name='블레이범',
            types=['불'],
            moves=move_data(['니트로차지', '오버히트', '불대문자', '와일드볼트', '지진', '치근거리기', '암석봉인', '섀도볼', '화염방사'], ['불']),
            sex='male',
            ability=ability_data(['맹화', '타오르는불꽃']),
            hp=76,
            attack=104,
            defense=71,
            sp_attack=104,
            sp_defense=71,
            speed=108,
            level=50
        ),
        PokemonInfo(
            id=154,
            name='메가니움',
            types=['풀'],
            moves=move_data(['씨뿌리기', '기가드레인', '광합성', '맹독', '방어', '에너지볼', '원시의힘', '지진', '바디프레스', '드래곤테일'], ['풀']),
            sex='female',
            ability=ability_data(['심록', '리프가드']),
            hp=80,
            attack=82,
            defense=100,
            sp_attack=83,
            sp_defense=100,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=160,
            name='장크로다일',
            types=['물'],
            moves=move_data(['용의춤', '아쿠아브레이크', '냉동펀치', '엄청난힘', '스톤샤워', '아쿠아제트', '깨물어부수기', '개척하기', '눈사태'], ['물']),
            sex='male',
            ability=ability_data(['급류', '우격다짐']),
            hp=85,
            attack=105,
            defense=100,
            sp_attack=79,
            sp_defense=83,
            speed=78,
            level=50
        ),
        PokemonInfo(
            id=257,
            name='번치코',
            types=['불', '격투'],
            moves=move_data(['칼춤', '플레어드라이브', '스톤에지', '인파이트', '블레이즈킥', '번개펀치', '유턴', '파동탄', '지진', '브레이브버드', '진공파', '깜짝베기'], ['불', '격투']),
            sex='male',
            ability=ability_data(['가속', '맹화']),
            hp=80,
            attack=120,
            defense=70,
            sp_attack=110,
            sp_defense=70,
            speed=80,
            level=50
        ),
        PokemonInfo(
            id=254,
            name='나무킹',
            types=['풀'],
            moves=move_data(['기가드레인', '용의파동', '씨뿌리기', '진공파', '에너지볼', '리프스톰', '암석봉인', '드래곤테일', '스톤샤워', '애크러뱃'], ['풀']),
            sex='male',
            ability=ability_data(['곡예', '심록']),
            hp=70,
            attack=85,
            defense=65,
            sp_attack=105,
            sp_defense=85,
            speed=120,
            level=50
        ),
        PokemonInfo(
            id=260,
            name='대짱이',
            types=['물', '땅'],
            moves=move_data(['퀵턴', '아쿠아브레이크', '지진', '눈사태', '스톤샤워', '암석봉인', '독찌르기', '카운터', '냉동펀치', '스텔스록'], ['물', '땅']),
            sex='male',
            ability=ability_data(['급류']),
            hp=100,
            attack=110,
            defense=90,
            sp_attack=85,
            sp_defense=90,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=392,
            name='초염몽',
            types=['불', '격투'],
            moves=move_data(['플레어드라이브', '번개펀치', '드레인펀치', '지진', '마하펀치', '인파이트', '애크러뱃', '니트로차지', '유턴', '오버히트', '풀묶기', '더스트슈트', '화염방사'], ['불', '격투']),
            sex='male',
            ability=ability_data(['맹화', '철주먹']),
            hp=76,
            attack=104,
            defense=71,
            sp_attack=104,
            sp_defense=71,
            speed=108,
            level=50
        ),
        PokemonInfo(
            id=389,
            name='토대부기',
            types=['풀', '땅'],
            moves=move_data(['껍질깨기', '지진', '우드해머', '기가드레인', '아이언헤드', '스톤샤워', '들이받기', '스톤에지', '스텔스록', '깨물어부수기'], ['풀', '땅']),
            sex='male',
            ability=ability_data(['조가비갑옷', '심록']),
            hp=95,
            attack=109,
            defense=105,
            sp_attack=75,
            sp_defense=85,
            speed=56,
            level=50
        ),
        PokemonInfo(
            id=395,
            name='엠페르트',
            types=['물', '강철'],
            moves=move_data(['퀵턴', '하이드로펌프', '냉동빔', '풀묶기', '아쿠아제트', '러스터캐논', '에어슬래시', '암석봉인', '날개쉬기'], ['물', '강철']),
            sex='male',
            ability=ability_data(['오기', '급류']),
            hp=84,
            attack=86,
            defense=88,
            sp_attack=111,
            sp_defense=101,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=500,
            name='염무왕',
            types=['불', '격투'],
            moves=move_data(['니트로차지', '플레어드라이브', '양날박치기', '와일드볼트', '개척하기', '독찌르기', '인파이트', '지진', '풀묶기', '드레인펀치'], ['불', '격투']),
            sex='male',
            ability=ability_data(['맹화', '이판사판']),
            hp=110,
            attack=123,
            defense=65,
            sp_attack=100,
            sp_defense=65,
            speed=65,
            level=50
        ),
        PokemonInfo(
            id=497,
            name='샤로다',
            types=['풀'],
            moves=move_data(['리프스톰', '기가드레인', '뱀눈초리', '용의파동', '드래곤테일', '에너지볼', '아쿠아테일'], ['풀']),
            sex='female',
            ability=ability_data(['심술꾸러기', '심록']),
            hp=75,
            attack=75,
            defense=95,
            sp_attack=75,
            sp_defense=95,
            speed=113,
            level=50
        ),
        PokemonInfo(
            id=503,
            name='대검귀',
            types=['물'],
            moves=move_data(['눈사태', '아쿠아브레이크', '퀵턴', '아쿠아제트', '풀묶기', '메가혼', '하이드로펌프', '에어슬래시', '땅고르기', '깜짝베기', '성스러운칼'], ['물']),
            sex='male',
            ability=ability_data(['급류', '조가비갑옷']),
            hp=95,
            attack=100,
            defense=85,
            sp_attack=108,
            sp_defense=70,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=655,
            name='마폭시',
            types=['불', '에스퍼'],
            moves=move_data(['매지컬플레임', '사이코키네시스', '에너지볼', '명상', '섀도볼', '불대문자', '이상한빛', '화염방사', '매지컬샤인'], ['불', '에스퍼']),
            sex='female',
            ability=ability_data(['맹화']),
            hp=75,
            attack=69,
            defense=72,
            sp_attack=114,
            sp_defense=100,
            speed=104,
            level=50
        ),
        PokemonInfo(
            id=652,
            name='브리가론',
            types=['풀', '격투'],
            moves=move_data(['씨기관총', '바디프레스', '광합성', '철벽', '맹독', '씨뿌리기', '바늘미사일', '암석봉인', '드레인펀치', '스톤샤워', '니들가드'], ['풀', '격투']),
            sex='male',
            ability=ability_data(['방탄', '심록']),
            hp=88,
            attack=107,
            defense=122,
            sp_attack=74,
            sp_defense=75,
            speed=64,
            level=50
        ),
        PokemonInfo(
            id=658,
            name='개굴닌자',
            types=['물', '악'],
            moves=move_data(['풀묶기', '하이드로펌프', '물수리검', '악의파동', '냉동빔', '독압정', '깜짝베기', '더스트슈트', '애크러뱃', '유턴'], ['물', '악']),
            sex='male',
            ability=ability_data(['변환자재', '급류']),
            hp=72,
            attack=95,
            defense=67,
            sp_attack=103,
            sp_defense=71,
            speed=122,
            level=50
        ),
        PokemonInfo(
            id=727,
            name='어흥염',
            types=['불', '악'],
            moves=move_data(['플레어드라이브', '도깨비불', '막말내뱉기', 'DD래리어트', '지진', '인파이트', '개척하기', '번개펀치', '불꽃펀치', '크로스촙'], ['불', '악']),
            sex='male',
            ability=ability_data(['위협', '맹화']),
            hp=95,
            attack=115,
            defense=90,
            sp_attack=80,
            sp_defense=90,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=724,
            name='모크나이퍼',
            types=['풀', '고스트'],
            moves=move_data(['리프블레이드', '칼춤', '폴터가이스트', '더블윙', '야습', '브레이브버드', '애크러뱃', '이상한빛', '개척하기', '섀도클로'], ['풀', '고스트']),
            sex='male',
            ability=ability_data(['심록']),
            hp=78,
            attack=107,
            defense=75,
            sp_attack=100,
            sp_defense=100,
            speed=70,
            level=50
        ),
        PokemonInfo(
            id=730,
            name='누리레느',
            types=['물', '페어리'],
            moves=move_data(['물거품아리아', '문포스', '퀵턴', '아쿠아제트', '에너지볼', '냉동빔', '섀도볼', '사이코키네시스', '드레인키스'], ['물', '페어리']),
            sex='female',
            ability=ability_data(['급류']),
            hp=80,
            attack=74,
            defense=74,
            sp_attack=126,
            sp_defense=116,
            speed=60,
            level=50
        ),
        PokemonInfo(
            id=815,
            name='에이스번',
            types=['불'],
            moves=move_data(['화염볼', '무릎차기', '칼춤', '유턴', '애크러뱃', '개척하기', '아이언헤드', '더스트슈트', '니트로차지'], ['불']),
            sex='female',
            ability=ability_data(['맹화', '리베로']),
            hp=80,
            attack=116,
            defense=75,
            sp_attack=65,
            sp_defense=75,
            speed=119,
            level=50
        ),
        PokemonInfo(
            id=812,
            name='고릴타',
            types=['풀'],
            moves=move_data(['그래스슬라이더', '10만마력', '칼춤', '우드해머', '드럼어택', '애크러뱃', '개척하기', '드레인펀치', '로킥'], ['풀']),
            sex='male',
            ability=ability_data(['그래스메이커', '심록']),
            hp=100,
            attack=125,
            defense=90,
            sp_attack=60,
            sp_defense=70,
            speed=85,
            level=50
        ),
        PokemonInfo(
            id=818,
            name='인텔리레온',
            types=['물'],
            moves=move_data(['기충전', '열탕', '냉동빔', '섀도볼', '에어커터', '하이드로펌프', '아쿠아제트', '악의파동'], ['물']),
            sex='male',
            ability=ability_data(['스나이퍼', '급류']),
            hp=70,
            attack=85,
            defense=65,
            sp_attack=125,
            sp_defense=65,
            speed=120,
            level=50
        ),
        PokemonInfo(
            id=911,
            name='라우드본',
            types=['불', '고스트'],
            moves=move_data(['플레어송', '게으름피우기', '섀도볼', '도깨비불', '오버히트', '대지의힘', '씨폭탄', '매혹의보이스'], ['불', '고스트']),
            sex='male',
            ability=ability_data(['맹화', '천진']),
            hp=104,
            attack=75,
            defense=100,
            sp_attack=110,
            sp_defense=75,
            speed=66,
            level=50
        ),
        PokemonInfo(
            id=908,
            name='마스카나',
            types=['풀', '악'],
            moves=move_data(['트릭플라워', '유턴', '깜짝베기', '치근거리기', '애크러뱃', '개척하기', '로킥', '트리플악셀', '찬물끼얹기'], ['풀', '악']),
            sex='female',
            ability=ability_data(['변환자재', '심록']),
            hp=76,
            attack=110,
            defense=70,
            sp_attack=81,
            sp_defense=70,
            speed=123,
            level=50
        ),
        PokemonInfo(
            id=914,
            name='웨이니발',
            types=['물', '격투'],
            moves=move_data(['아쿠아스텝', '웨이브태클', '인파이트', '브레이브버드', '아쿠아브레이크', '트리플악셀', '로킥', '유턴'], ['물', '격투']),
            sex='male',
            ability=ability_data(['자기과신', '급류']),
            hp=85,
            attack=120,
            defense=80,
            sp_attack=85,
            sp_defense=75,
            speed=85,
            level=50
        )
    ]